import type { Metadata } from 'next/types'

import { titleMerge } from '@/configs/seoConfig'

import AccountReferral from '@/views/Account/views/AccountReferral'

export const metadata: Metadata = {
  title: titleMerge('Referral Program'),
  description: 'Generated by create next app',
}

export default function Referral() {
  return <AccountReferral />
}
