import type { Metadata } from 'next/types'

import { titleMerge } from '@/configs/seoConfig'

import PrivacyPolicyView from '@/views/PrivacyPolicy'

export const metadata: Metadata = {
  title: titleMerge('Privacy Policy'),
  description: 'Generated by create next app',
}

export default function Home() {
  return <PrivacyPolicyView />
}
