import type { Metadata } from 'next/types'

import { titleMerge } from '@/configs/seoConfig'

import AccountDashboard from '@/views/Account/views/AccountDashboard'

export const metadata: Metadata = {
  title: titleMerge('Dashboard'),
  description: 'Generated by create next app',
}

export default function Account() {
  return <AccountDashboard />
}
