import type { Metadata } from 'next/types'

import { titleMerge } from '@/configs/seoConfig'

import HomeView from '@/views/Home'

export const metadata: Metadata = {
  title: titleMerge('Home'),
  description: 'Generated by create next app',
}

export default function Home() {
  return <HomeView />
}
