import type { Metadata } from 'next/types'

import { titleMerge } from '@/configs/seoConfig'

import AccountInventory from '@/views/Account/views/AccountInventory'

export const metadata: Metadata = {
  title: titleMerge('Inventory'),
  description: 'Generated by create next app',
}

export default function Inventory() {
  return <AccountInventory />
}
