import type { Metadata } from 'next/types'

import { titleMerge } from '@/configs/seoConfig'

import TermsOfUseView from '@/views/TermsOfUse'

export const metadata: Metadata = {
  title: titleMerge('Terms of Use'),
  description: 'Generated by create next app',
}

export default function Home() {
  return <TermsOfUseView />
}
