import type { Metadata } from 'next/types'

import { titleMerge } from '@/configs/seoConfig'

import AccountShop from '@/views/Account/views/AccountShop'

export const metadata: Metadata = {
  title: titleMerge('Shop'),
  description: 'Generated by create next app',
}

export default function Shop() {
  return <AccountShop />
}
